export type ENV = {
  DATABASE: string | undefined;
  JWT_SECRET: string | undefined;
  PORT: string | undefined;
  CLIENT_URL: string | undefined;
  EMAIL_NAME: string | undefined;
  EMAIL_USER: string | undefined;
  EMAIL_HOST: string | undefined;
  EMAIL_PORT: number | undefined;
  EMAIL_SECURE: boolean | undefined;
  EMAIL_PASSWORD: string | undefined;
  AWS_ACCESS_KEY_ID: string | undefined;
  AWS_SECRET_ACCESS_KEY: string | undefined;
  AWS_REGION: string | undefined;
  AWS_BUCKET_NAME: string | undefined;
};
export type Config = {
  DATABASE: string;
  JWT_SECRET: string;
  PORT: string;
  CLIENT_URL: string;
  EMAIL_NAME: string;
  EMAIL_USER: string;
  EMAIL_HOST: string;
  EMAIL_PORT: number;
  EMAIL_SECURE: boolean;
  EMAIL_PASSWORD: string;
  AWS_ACCESS_KEY_ID: string;
  AWS_SECRET_ACCESS_KEY: string;
  AWS_REGION: string;
  AWS_BUCKET_NAME: string;
};
